networks:
  airflow_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  webserver:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "XvLWeJ9zZ4fD9x1Qmk+YFg=="
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_12345"
      AIRFLOW__WEBSERVER__WORKERS: 1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow_network

  scheduler:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "XvLWeJ9zZ4fD9x1Qmk+YFg=="
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_super_secret_key_12345"
    depends_on:
      - webserver
      - postgres
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow_network

volumes:
  postgres_data:
